In [12]:
import pandas as pd
import numpy as np

#docs = pd.read_csv('data.csv')

np.random.seed(42)

# Generating synthetic data for the dataset
data = {
    'age': np.random.randint(18, 65, size=100),  # Random ages between 18 and 65
    'salary': np.random.randint(30000, 150000, size=100),  # Random salary between 30,000 and 150,000
    'previous_purchases': np.random.randint(0, 10, size=100),  # Random previous purchase counts between 0 and 10
    'will_buy': np.random.randint(0, 2, size=100)  # Random binary target variable (0 or 1)
}

# Creating a DataFrame from the generated data
df = pd.DataFrame(data)
df_cleaned = df.dropna() # drop missing values
df_cleaned.head()

age  salary  previous_purchases  will_buy
0   56   32695                   2         1
1   46   78190                   6         1
2   32   35258                   5         1
3   60  117538                   7         1
4   25   69504                   8         1

 task is to implement a Logistic Regression model to classify customers into two classes: "will buy" and "will not buy".

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


X = df_cleaned[['age','salary','previous_purchases']]
y = df_cleaned[['will_buy']]

scaler = StandardScaler() 

X_std = scaler.fit_transform(X)

# Create a DataFrame with the standardized features
df_standardized = pd.DataFrame(X_std, columns=['age', 'salary', 'previous_purchases'])

# Add the target variable back to the standardized DataFrame
df_standardized['will_buy'] = y.values

print("Standardized DataFrame:")
print(df_standardized)

Standardized DataFrame:
         age    salary  previous_purchases  will_buy
0   1.086153 -1.637760           -0.691465         1
1   0.367798 -0.353444            0.684585         1
2  -0.637899 -1.565406            0.340572         1
3   1.373495  0.757343            1.028597         1
4  -1.140748 -0.598648            1.372610         1
..       ...       ...                 ...       ...
95 -1.212584  0.173099            1.028597         1
96 -1.068913  0.018710           -1.379490         0
97  0.008620 -1.522554            1.028597         0
98 -1.643597  0.905521           -0.347453         0
99  1.445331 -0.160747           -1.379490         1

[100 rows x 4 columns]


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.2, random_state=42)

model = LogisticRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

# Calculate and print metrics from the confusion matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Confusion Matrix:")
print(cm)
print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")


Confusion Matrix:
[[4 3]
 [4 9]]

Evaluation Metrics:
Accuracy: 0.65
Precision: 0.75
Recall: 0.69
F1 Score: 0.72


/Users/berkgungor/.pyenv/versions/3.9.6/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Model improvement

In [19]:
#Hyperparameter Tuning: Grid Search
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.01, 0.1, 1, 10, 100]}
grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_
best_model.fit(X_train,y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

/Users/berkgungor/.pyenv/versions/3.9.6/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/berkgungor/.pyenv/versions/3.9.6/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/berkgungor/.pyenv/versions/3.9.6/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/berkgungor/.pyenv/versions/3.9.6/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A 

array([[4, 3],
       [4, 9]])

In [22]:
#regularization

model = LogisticRegression(penalty='l2', C=1.0)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print(cm,f1)

[[4 3]
 [4 9]] 0.72


/Users/berkgungor/.pyenv/versions/3.9.6/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
